### ISSUE TITLE
Cela est infonctionnel

### ISSUE THREAD

**Issue by LouisGrx** [jneb92jneb92/PiedPiper_MediaCenter#1]
Cela ne fonctionne pas quand je clique!?

**Comment by jneb92jneb92** [comment]
Il suffit de cliquer le bouton "Réparer, en cliquant ici". Ceci est un lien hypertexte qui résoudra tout vos problèmes. Merci pour l'attention que vous prêtez à ce projet.

Yes,
Jojonaben
